# This file was generated by GoReleaser. DO NOT EDIT.
cask "feat" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/feat"], must_succeed: false
    end
  end

  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "eed85b07816291c8b4c1434b38fa0b3aac3bd3d1c379973c6a1f57277edd5383"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_darwin_amd64.tar.gz"
      rename "feat_0.3.0_darwin_amd64/feat", "feat"
    end
    on_arm do
      sha256 "f2962cd273b92be2427e7e53da65e44ca9aaaa24b4d2b9e09ebeeb6349fabbc2"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_darwin_arm64.tar.gz"
      rename "feat_0.3.0_darwin_arm64/feat", "feat"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f530466524c0204fe2634c54c74fe56a1a4fb65463ca9a06e56123f419fe449"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_linux_amd64.tar.gz"
      rename "feat_0.3.0_linux_amd64/feat", "feat"
    end
    on_arm do
      sha256 "340212bc692d5195b563f7db51aee69d6c615bde3c7ef927037ca72160664118"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_linux_arm64.tar.gz"
      rename "feat_0.3.0_linux_arm64/feat", "feat"
    end
  end

  name "feat"
  desc "Terminal-native control plane for running several coding agents at once"
  homepage "https://github.com/ma8el/feat"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "feat"

  # No zap stanza required

  caveats <<~EOS
    Feat launches Claude Code and has no agent of its own. Install it and sign
    in, then run `feat doctor`:
      https://code.claude.com/docs/en/setup
  EOS
end
