# This file was generated by GoReleaser. DO NOT EDIT.
cask "feat" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e30319b0b6714bfdf12b55a50e289fce4f253c67412ebad6b57bfbcdb8a90321"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_darwin_amd64.tar.gz"
      rename "feat_0.2.0_darwin_amd64/feat", "feat"
    end
    on_arm do
      sha256 "e1ab602a0d34075e522bb3059f00b1d206528680aca315a89a79de4c7aa764ef"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_darwin_arm64.tar.gz"
      rename "feat_0.2.0_darwin_arm64/feat", "feat"
    end
  end

  on_linux do
    on_intel do
      sha256 "7262408e6d3976a3b9d819d1d9cafae434ccc6b349d5e4530b6ccc419642b034"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_linux_amd64.tar.gz"
      rename "feat_0.2.0_linux_amd64/feat", "feat"
    end
    on_arm do
      sha256 "65c43980fd08c04e91f655224a7ef1f634811066a2ecad7d4da24fd8d373afa6"
      url "https://github.com/ma8el/feat/releases/download/v#{version}/feat_#{version}_linux_arm64.tar.gz"
      rename "feat_0.2.0_linux_arm64/feat", "feat"
    end
  end

  name "feat"
  desc "Terminal-native control plane for running several coding agents at once"
  homepage "https://github.com/ma8el/feat"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "feat"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/feat"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Feat launches Claude Code and has no agent of its own. Install it and sign
    in, then run `feat doctor`:
      https://code.claude.com/docs/en/setup
  EOS
end
